services:
  # --------------------------
  # Backend Service
  # --------------------------
  - type: web
    name: vehicle-yard-backend
    env: node
    rootDir: backend
    buildCommand: |
      npm install --include=dev
      npx prisma generate
      npx prisma migrate deploy
      node src/seed.js
    startCommand: node src/server.js
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromSecret: postgres://avnadmin:AVNS_mapiXLN31OsYZzt0Hj-@pg-3ca8b90c-vehicleyard1.h.aivencloud.com:21603/defaultdb?sslmode=require
      - key: PORT
        value: "4000"


  # --------------------------
  # Frontend Service
  # --------------------------
  - type: web
    name: vehicle-yard-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        fromSecret: https://vehicle-yard-backend.onrender.com
